project:
  type: website
  output-dir: _site

website:
  title: "Data Science for Social Good"
  description: "Homepage for MATH 185 Fall 23"
  site-url: "https://norcalbiostat.github.io/DATA185"
  page-navigation: true

    
  page-footer:
    #background: light
    left: "This site is built with :heart:, {{< fa brands r-project >}} and [Quarto](https://quarto.org/) by [Robin Donatello](www.norcalbiostat.com)."
   
  navbar:
    pinned: true
    background: "#FF8C00"
    left:
      - text: Modules
        href: module_list.qmd
      - text: Learn
      - text: Practice
      - text: Apply

        
    right: 
      - text: Syllabus
        href: syllabus.qmd

  sidebar:
    - id: modules
      title: "Modules"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - text: "Welcome"
          href: module_overview/welcome.qmd
          
    - id: learn
      title: "Learn"
      
    - id: Practice
      title: "Practice"
      
    - id: Apply
      title: "Apply"
      
      

from: markdown+emoji
format:
  html:
    highlight-style: a11y
    theme: 
      light: flatly
      dark: darkly
    highlight: pygments
    toc: true
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

execute:
  freeze: auto # re-render only when source changes
  echo: false
  warning: false
