project:
  type: website
  output-dir: _site

website:
  title: "Data Science for Social Good"
  description: "Homepage for MATH 185 Fall 23"
  site-url: "https://norcalbiostat.github.io/DATA185"
  page-navigation: true

    
  page-footer:
    #background: light
    left: "This site is built with :heart:, {{< fa brands r-project >}} and [Quarto](https://quarto.org/) by [Robin Donatello](www.norcalbiostat.com)."
   
  navbar:
    pinned: true
    background: "#0099CC"
    left:
      - text: Notes
        href: notes_list.qmd
      - text: Practice
        href: practice_list.qmd
      - text: Apply
        href: project.qmd
      - text: Learning R (TBD)
        

        
    right: 
      - text: Syllabus
        href: syllabus.qmd

  sidebar:
    - id: guide
      title: "All Materials"
      style: "floating"
      align: left
      contents:
        - section: "Notes"
          href: notes_list.qmd
          contents: 
            - notes/cn00-welcome.qmd
            - notes/cn01-data_literacy.qmd
        - section: "Practice"
          href: practice_list.qmd
          contents:
            - practice/lab01-computing.qmd
            - practice/lab02-excel.qmd

from: markdown+emoji
format:
  html:
    highlight-style: a11y
    theme: 
      light: flatly
      dark: darkly
    highlight: pygments
    toc: true
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

execute:
  freeze: auto # re-render only when source changes
  echo: false
  warning: false
