---
title: "Data Science for Social Good"
subtitle: |
  MATH 185 • Fall 2023 <br> California State University, Chico
toc: false
sidebar: false
page-layout: full
---


## Course Information

Data are not neutral, nor are the algorithms that control how the data that governs our lives are used. Interpretations and recommendations made using data are subjective. This course introduces students how to start harnessing the power of data to intelligently cope with the requirements of citizenship, employment, and family to be prepared for a healthy, happy and productive life.

Students will practice collecting and wrangling data into a usable form, visualizing large data sets to discover patterns, representing data in a meaningful way, exploring varying interpretations of the data and results, and discussing potentials for misuse and abuse. This course promotes critical reflection on the ethical, social, cultural, and political dimensions of data as well as providing direct hands on experience with both spreadsheets, and the programming language R.

Students from all majors are welcome! **No prior programming experience is expected**, however basic ability to use a computer is needed. Additional help is available for students needing extra support with either/both computers or math.

::: {.grid .course-details}


::: {.g-col-4}
### Course details

{{< fa calendar >}} &nbsp; {{< var course.days >}}
{{< fa clock >}} &nbsp; {{< var course.time >}}
{{< fa location-dot >}} &nbsp; {{< var course.location >}}
{{< fa people-roof >}} &nbsp; {{< var course.moi >}}
:::


::: {.g-col-4}
#### Pre-reqs
{{< var course.pre_req >}}

#### Student Drop in Hours
{{< var course.oh >}}

:::



::: {.g-col-4}
### Instructor

{{< fa user >}} &nbsp; [{{< var instructor.name >}}]({{< var instructor.url >}})
{{< fa university >}} &nbsp; {{< var instructor.office >}}
{{< fa envelope >}} &nbsp; <a href="mailto:{{< var instructor.email >}}">{{< var instructor.email >}}</a>  
{{< fa calendar-check >}} &nbsp; [Schedule an appointment]({{< var instructor.appointment_url >}})
:::

:::


:::{.callout-tip}
You can toggle dark mode by clicking the {{< fa toggle-off >}} button in the top right navigation bar.
:::